parameters:
- name: py_version
  type: string
  default: ''
- name: image
  type: string
  default: ''
- name: ccache
  type: boolean
  default: false
- name: OSX_VERSION
  type: string
  default: ''
- name: conda_package_root
  type: string
  default: ''
- name: conda_env
  type: string
  default: ''
- name: conda_channels
  type: string
  default: ''
- name: verbose
  type: boolean
  default: false
- name: noarch
  type: boolean
  default: false

jobs:
  - job:
    timeoutInMinutes: 120
    displayName: ${{ format('{0}-py{1}', parameters.image, parameters.py_version) }}
    pool:
      vmImage: ${{ parameters.image }}
    variables:
      - name: OSX_VERSION
        value: ${{ parameters.OSX_VERSION }}
      - name: VERBOSE_OPTION
        value: ''

    steps:
      - checkout: self
        submodules: true

      - ${{ if eq(parameters.ccache, true) }}:
        - template: ccache.yml

      # Note that using set -ex when setting vso variables messes up paths
      - ${{ if contains(parameters.image, 'windows') }}:
        - bash: |
            echo "##vso[task.prependpath]$CONDA\Scripts"
            echo "##vso[task.setvariable variable=scipp_install_prefix]$CONDA\scipp_install"
          displayName: 'Configure Conda path'
      - ${{ if not(contains(parameters.image, 'windows')) }}:
        - bash: |
            echo "##vso[task.prependpath]$CONDA/bin"
            echo "##vso[task.setvariable variable=scipp_install_prefix]$CONDA/scipp_install"
          displayName: 'Configure Conda path'

      - bash: |
          echo "##vso[task.setvariable variable=conda_dir]$CONDA"
        displayName: 'Configure Conda dir'
      - ${{ if not(eq(length(parameters.OSX_VERSION), 0)) }}:
        - bash: |
            set -ex
            sudo chown -R $USER $CONDA
          displayName: 'Take ownership of Conda installation'

      - bash: |
          set -ex
          conda --version
          conda install --yes -c conda-forge conda-build -n base
          conda install --yes -c conda-forge mamba -n base
          conda config --set always_yes yes --set changeps1 no
        displayName: 'Install conda-build'

      - bash: |
          if test -f tools/build_cpp.py; then
             echo "##vso[task.setvariable variable=buildcppfileexists]true"
          fi
        displayName: 'Check for existence of cpp build file'

      - bash: |
          set -ex
          sed 's/- python$/- python=${{ parameters.py_version }}/g' ${{ parameters.conda_env }} > tempenv.yml
          conda env create -f tempenv.yml -n tempenv
          source activate tempenv
        displayName: 'Create conda environment with conda'
      - bash: |
          set -ex
          sed 's/- python$/- python=${{ parameters.py_version }}/g' ${{ parameters.conda_env }} > other.yml
          source activate base
          python --version
          ls $CONDA_PREFIX\\lib\\site-packages\\mamba\\
          mamba --version
          mamba env create -f other.yml -n other
        displayName: 'Create conda environment with mamba'

      - bash: |
          set -ex
          source activate base
          mamba env list
          conda activate tempenv
          conda activate other
          python tools/build_cpp.py --prefix=$SCIPP_INSTALL_PREFIX
        displayName: 'Build and run C++ tests'
        condition: eq(variables['buildcppfileexists'], 'true')

      - ${{ if eq(parameters.verbose, true) }}:
        - bash: |
            echo "##vso[task.setvariable variable=verbose_option]--debug"
          displayName: 'Activate conda build debug mode'

      - bash: |
          if [ '${{ parameters.noarch }}' == 'True' ]; then
            echo "##vso[task.setvariable variable=conda_package_folder]noarch"
          else
            echo "##vso[task.setvariable variable=conda_package_folder]${{ parameters.conda_package_root }}"
            echo "##vso[task.setvariable variable=set_python_version]--python=${{ parameters.py_version }}"
          fi
        displayName: 'Set package folder'

      - bash: |
          set -ex
          source activate other
          mamba build $VERBOSE_OPTION \
            --channel conda-forge ${{ parameters.conda_channels }} \
            $SET_PYTHON_VERSION \
            --no-anaconda-upload \
            --override-channels \
            conda
        displayName: 'Python tests and conda build'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(conda_dir)/conda-bld/$(conda_package_folder)"
          ArtifactName: "${{ parameters.conda_package_root }}-py${{ parameters.py_version }}"
        displayName: 'Archive Conda package artifacts'

      - ${{ if eq(parameters.ccache, true) }}:
        - bash: ccache --show-stats
          displayName: 'Report ccache statistics'
