parameters:
- name: settings
  type: object
  default:
    linux:
      image: 'ubuntu-20.04'
      conda_package_root: 'linux-64'
      params:
        ccache: true
    osx:
      image: 'macOS-11'
      conda_package_root: 'osx-64'
      params:
        OSX_VERSION: '10.15'
    windows:
      image: 'windows-latest'
      conda_package_root: 'win-64'
      params:
        clcache: true
- name: config
  type: object
  default: []
- name: package
  type: boolean
  default: false
- name: deploy  # Used only when package=true
  type: boolean
  default: false
- name: release
  type: boolean
  default: false
- name: conda_label
  type: string
  default: 'test'
- name: conda_env
  type: string
  default: ''
- name: conda_channels
  type: string
  default: ''
- name: gh_pages_subdirectory
  type: string
  default: ''
- name: verbose
  type: boolean
  default: false
- name: publish_docs
  type: boolean
  default: true
- name: noarch
  type: boolean
  default: false

stages:
  - ${{ if not(eq(parameters.deploy, true)) }}:
    - template: code_quality_checks.yml
      parameters:
        image: ${{ parameters.settings.linux.image }}
    - stage: 'build_and_test'
      displayName: 'Build and Test'
      jobs:
        - ${{ each os in parameters.config }}:
          - ${{ each py in os.Value.py_versions }}:
            - template: build.yml
              parameters:
                verbose: ${{ parameters.verbose }}
                py_version: ${{ py }}
                image: ${{ parameters.settings[os.Key].image }}
                conda_package_root: ${{ parameters.settings[os.Key].conda_package_root }}
                conda_env: ${{ os.Value.conda_env }}
                noarch: ${{ parameters.noarch }}
                ${{ each param in parameters.settings[os.Key].params }}:
                  ${{ param.Key }}: ${{ param.Value }}


  - ${{ if eq(parameters.package, true) }}:
    - stage: 'package_build_and_test'
      displayName: 'conda build'
      jobs:
        - ${{ each os in parameters.config }}:
          - ${{ each py in os.Value.py_versions }}:
            - template: package-build.yml
              parameters:
                verbose: ${{ parameters.verbose }}
                py_version: ${{ py }}
                image: ${{ parameters.settings[os.Key].image }}
                conda_package_root: ${{ parameters.settings[os.Key].conda_package_root }}
                conda_env: ${{ os.Value.conda_env }}
                conda_channels: ${{ parameters.conda_channels }}
                noarch: ${{ parameters.noarch }}
                ${{ each param in parameters.settings[os.Key].params }}:
                  ${{ param.Key }}: ${{ param.Value }}
    - ${{ if eq(parameters.deploy, true) }}:
      - template: deploy.yml
        parameters:
          image: ${{ parameters.settings.linux.image }}
          release: ${{ parameters.release }}
          publish_docs: ${{ parameters.publish_docs }}
          conda_label: ${{ parameters.conda_label }}
          gh_pages_subdirectory: ${{ parameters.gh_pages_subdirectory }}
          publish_package: true
          package_list:
            ${{ each os in parameters.config }}:
              ${{ each py in os.Value.py_versions }}:
                ${{ parameters.settings[os.Key].conda_package_root }}-py${{ py }}: true
