package:
  name: pipelines-test
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 11.1.* [linux64]
    - git
    - ninja
    - python
  run:
    - python

test:
  requires:
    - pytest
    - sphinx
    - sphinx_rtd_theme
  source_files:
    - python/tests
    - docs/
  script_env:
    - DOCS_BUILD_DIR
  commands:
    - python -m pytest -v python
    - python docs/build_and_test.py [not win]

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script:
    - python tools/build_cpp.py

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Test of common Azure pipelines repo for scipp
  description: Test of common Azure pipelines repo for scipp
  dev_url: https://github.com/scipp/pipelines
  doc_url: https://scipp.github.io/

extra:
  developer_dependencies:
    - pre-commit
    - yapf
    - flake8
