parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  - main

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: ../pipelines/stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: 'conda-forge'
    config:
      linux:
        py_versions: ['3.7']
      osx:
        py_versions: ['3.7']
      windows:
        py_versions: ['3.7']
    # Note: At this point we are not testing deploy and release.
    # Consider setting up a build matrix.
    deploy: false
    conda_label: 'dev'
    release: true
