parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: ../pipelines/stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        # Builds both a noarch package (scippbuildtools) and dummy C++/pybind package
        py_versions: ['noarch', '3.7']
        conda_env: 'pipelines-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'pipelines-developer.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'pipelines-developer.yml'
    deploy: true
    publish_docs: false
    conda_label: 'dev'
